fix to get default storage from cookie
arbolista-dev/generator-spike pull request #13
Opened 2017-05-22 19:05 UTC by daruj

2017-05-22 19:13 UTC, Arbolista commented on src/generators/app/templates/src/client/index.jsx
> +load(store);
creo que nada mas `storage.createLoader(storageEngine)(store);` - es mas leible.

2017-05-22 19:13 UTC, Arbolista commented on src/generators/app/templates/src/server/renderReact.jsx
> +  const load = storage.createLoader(storageEngine);
tambien aqui: `storage.createLoader(storageEngine)(store);`.

2017-05-24 01:16 UTC, erichulburd requested changes

2017-05-24 01:16 UTC, Arbolista commented on src/generators/app/templates/src/server/configureApp.js
> +          content = renderReact(req.i18n, req.originalUrl, {}, store);
`content = renderReact(req.i18n, req.originalUrl, context, store);`

2017-05-24 01:16 UTC, Arbolista commented on src/generators/app/templates/src/server/renderReact.jsx
> +export default function renderReact(i18n, location, context = {}, store) {
`export default function renderReact(i18n, location, context, store) {`

2017-05-24 01:16 UTC, Arbolista commented on src/generators/app/templates/src/shared/routes/CustomRoute.jsx
> +        staticContext.status = code;
Para que sirve esto? Pense que ReactRouter hace esto automaticamente?

2017-05-24 01:18 UTC, Arbolista commented on src/generators/app/templates/src/shared/routes/CustomRoute.jsx
> +const CustomRoute = ({
Creo que necesita un nombre mas especifico - `SwitchRoute`, `AuthConfiguredRoute`, etc.

2017-05-24 01:20 UTC, daruj commented on src/generators/app/templates/src/shared/routes/CustomRoute.jsx
> +        staticContext.status = code;
there is no `staticContext` on the client, so we need to guard against that here

2017-05-24 01:32 UTC, merged